version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g @angular/cli
      - npm i
  build:
    commands:
      - ng build --configuration=$DEPLOY_ENV
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - 'dist-*/**/*'
