version: 0.2

phases:
  build:
    runtime-versions:
      nodejs: latest
    commands:
      - npm i
      - ng build --configuration=dev
  cache:
    paths:
      - 'node_modules/**/*'
  artifacts:
    files:
      - 'dist/**/*'
